version: 2
updates:
  # Enable version updates for pnpm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    package-manager: 'pnpm'
    open-pull-requests-limit: 10
    target-branch: 'main'
    # Labels on pull requests for version updates
    labels:
      - 'dependencies'
    # Assign pull requests to specific reviewers
    # reviewers:
    #   - "your-github-username"
    # Ignore certain dependencies (optional)
    # ignore:
    #   - dependency-name: "express"
    #     versions: ["4.x", "5.x"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    # Workflow files stored in the default location of `.github/workflows`
    directory: '/'
    # Check for updates once a week
    schedule:
      interval: 'weekly'
