export const queryKeys = {
    players: 'players-list',
    droptimizers: 'droptimizers-list',
    droptimizersLastByCharDiff: 'droptimizer-last-char-diff',
    raidLootTable: 'raid-loot-table',
    raidSessions: 'raid-session-list',
    raidSessionsWithLoots: 'raid-session-list-with-loots',
    raidSession: 'raid-session',
    raidProgression: 'raid-progression',
    character: 'character',
    characterGameInfo: 'character-game-info',
    characters: 'character-list',
    charactersSummary: 'character-summary-list',
    characterInventory: 'characters-by-itemid',
    itemSearch: 'item-search',
    appSettings: 'app-settings',
    lootsBySession: 'loots-by-session',
    lootsAssignInfo: 'loots-assign-info',
    bosses: 'boss-list',
    // bis list,
    bisList: 'bis-list-get',
    // item note,
    itemNote: 'item-note',
    allItemNotes: 'all-item-notes'
}
