name: Linux Build
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VITE_TITLE: ${{ secrets.VITE_TITLE }}
      VITE_APPID: ${{ secrets.VITE_APPID }}
      MAIN_VITE_DATABASE_URL: ${{ secrets.MAIN_VITE_DATABASE_URL }}

    strategy:
      matrix:
        node: ['22']

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Build
        if: github.ref == 'refs/heads/main'
        run: pnpm run build:linux
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        if: github.ref != 'refs/heads/main'
        run: pnpm run build:linux --publish=never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        name: Upload AppImage
        with:
          name: WeakAuras-Companion-CI-AppImage
          path: dist/**/*.AppImage

