name: Linux Build
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['22']

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Build
        if: github.ref == 'refs/heads/main'
        run: pnpm run build:linux
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build
        if: github.ref != 'refs/heads/main'
        run: pnpm run build:linux --publish=never
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - uses: actions/upload-artifact@v4
        name: Upload AppImage
        with:
          name: WeakAuras-Companion-CI-AppImage
          path: dist/**/*.AppImage

      - uses: actions/upload-artifact@v4
        name: Upload Snap
        with:
          name: WeakAuras-Companion-CI-Snap
          path: dist/**/*.snap

      - uses: actions/upload-artifact@v4
        name: Upload deb
        with:
          name: WeakAuras-Companion-CI-deb
          path: dist/**/*.deb
