name: Windows Build

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write
      packages: write

    env:
      VITE_TITLE: ${{ secrets.VITE_TITLE }}
      VITE_APPID: ${{ secrets.VITE_APPID }}

    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Run tests
        run: pnpm test

      - name: Build
        run: pnpm run build:win --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get package version
        id: package_version
        run: echo "APP_VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v5
        name: Upload Installer
        with:
          name: ProjectOne-Companion-CI-${{ env.APP_VERSION }}-Installer
          path: dist/**/*Installer*.exe
