name: Windows Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      VITE_TITLE: ${{ secrets.VITE_TITLE }}
      VITE_APPID: ${{ secrets.VITE_APPID }}
      MAIN_VITE_DATABASE_URL: ${{ secrets.MAIN_VITE_DATABASE_URL }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Run tests
        run: pnpm test

      - name: Build
        run: pnpm run build:win --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        name: Upload Installer
        with:
          name: ProjectOne-Companion-CI-Installer
          path: dist/**/*Setup*.exe
